import type { Metadata } from "next";
import { IranYekan, geist } from "@/ui/fonts";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import ThemeToggle from "../ui/themeToggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => {
  return (
    <html
      lang="en"
      className={`${IranYekan.variable} ${geist.variable} h-full font-iranYekan antialiased`}
      dir={"rtl"}
      suppressHydrationWarning
    >
      <body className="min-h-full text-black dark:text-white bg-white dark:bg-darkBg">
        <ThemeProvider attribute={`data-theme`} defaultTheme={`system`}>
          {children}
          <ThemeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
