import type { Metadata } from "next";
import { IranSans, geist } from "@/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: LayoutProps<"/">) => {
  return (
    <html
      lang="en"
      className={`${IranSans.variable} ${geist.variable} h-full font-iranSans antialiased`}
      dir={'rtl'}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

export default RootLayout;